#!/bin/bash
config="/etc/justbrowsing/data/config"

if [ -f "$config" ]; then
  MOZILLA_LANG=$(grep ^locale "$config" | awk -F = '{print $NF}' | awk '{print $NF}' | sed 's/_/-/g')
  HOMEPAGE=$(grep ^url "$config" | awk -F = '{print $NF}' | awk '{print $NF}')
  export MOZILLA_LANG HOMEPAGE
fi

if [ ! -z "$HOMEPAGE" -a -z "$1" ]; then
  /usr/bin/firefox "$HOMEPAGE" -UILocale "$MOZILLA_LANG"
else
  /usr/bin/firefox $@ -UILocale "$MOZILLA_LANG"
fi
