#!/bin/bash
#############################
### google-chrome-wrapper ###
#############################

# Place in PATH before /usr/bin

config="/etc/justbrowsing/data/config"

if [ -f "$config" ]; then
  LANGUAGE=$(grep ^locale "$config" | awk -F = '{print $NF}' | awk '{print $NF}' | awk -F "-" '{print $1}')
  HOMEPAGE=$(grep ^url "$config" | awk -F = '{print $NF}' | awk '{print $NF}')
  KIOSK=$(grep ^kiosk "$config" | awk -F = '{print $NF}' | awk '{print $NF}')
  [ -z "$LANGUAGE" ] && LANGUAGE="en_US"
  export LANGUAGE HOMEPAGE KIOSK
fi

input="$HOMEPAGE"
[ ! -z "$1" ] && input="$@"

if [ "$KIOSK" = "true" ]; then
  /usr/bin/google-chrome $input --kiosk --no-first-run
else
  /usr/bin/google-chrome $input --no-first-run
fi
