#!/bin/bash
####################
### loadconfig #####
version=0.6 ########
### JustBrowsing ###
####################

probeDevice="/dev/disk/by-label/JUSTDATA"
mntDir="/etc/justbrowsing/mount"
saveDir="/etc/justbrowsing/data"
configFile="${saveDir}/config"
cfgFile="${mntDir}/justbrowsing.cfg"

EXIT_STATUS() { echo "ERROR: $@"; exit 1; }

PARSE_BOOT() { 
  cat /proc/cmdline 2>/dev/null | grep -o "$1=\S*" | awk -F = '{print $2}' | tail -n 1; 
}

MULTIPARSE_BOOT() {
  cat /proc/cmdline 2>/dev/null | grep -o "$1=\S*" | awk -F = '{print $2}';
}

OVERRIDE_CONFIG() {
  parameter=$(eval echo \$$1);
  if [ ! -z "$parameter" ]; then
    sed -i "/^$1/d" "$configFile"
    IFS=" "
    for arg in $parameter; do
      echo "$1 = $arg" >> "$configFile"
    done
  fi
}

# Skip loading config
skipcfg=$(PARSE_BOOT skipcfg)

# Load config from persistent storage
if [ -b "$probeDevice" -a "$skipcfg" != "true" ]; then
  [ "$UID" = "0" ] || EXIT_STATUS "Need to be root"
  mkdir -p "$mntDir" "$saveDir" || EXIT_STATUS "unable to create dirs: $mntDir $saveDir"
  mount -o ro "$probeDevice" "$mntDir" || EXIT_STATUS "unable to mount $probeDevice"
  [ -f "$cfgFile" ] &&
  cp "$cfgFile" "$configFile"
  umount "$mntDir" 2>/dev/null || EXIT_STATUS "unable to unmount $mntDir"
fi

# Load config from boot parameters
display=$(PARSE_BOOT display)
zone=$(PARSE_BOOT zone)
keymap=$(PARSE_BOOT keymap)
locale=$(PARSE_BOOT locale)
clean=$(PARSE_BOOT clean)
gpu=$(PARSE_BOOT gpu)
url=$(PARSE_BOOT url)
backlight=$(PARSE_BOOT backlight)
idle=$(PARSE_BOOT idle)
volume=$(PARSE_BOOT volume)
mouse=$(PARSE_BOOT mouse)
touchpad=$(PARSE_BOOT touchpad)
default=$(PARSE_BOOT default)
[ "$default" = "chrome" ] && default="google-chrome"
printer=$(MULTIPARSE_BOOT printer)

# Override config with boot parameters
mkdir -p "$saveDir" || EXIT_STATUS "unable to create $saveDir"
OVERRIDE_CONFIG display
OVERRIDE_CONFIG zone
OVERRIDE_CONFIG keymap
OVERRIDE_CONFIG locale
OVERRIDE_CONFIG clean
OVERRIDE_CONFIG gpu
OVERRIDE_CONFIG url
OVERRIDE_CONFIG backlight
OVERRIDE_CONFIG idle
OVERRIDE_CONFIG volume
OVERRIDE_CONFIG mouse
OVERRIDE_CONFIG touchpad
OVERRIDE_CONFIG default
OVERRIDE_CONFIG printer

chown -R user:users "$saveDir"

### END ###
