#!/bin/bash
####################
### saveconfig #####
version=1.0 ########
### JustBrowsing ###
####################

probeDevice="/dev/disk/by-label/JUSTDATA"
mntDir="/etc/justbrowsing/mount"
saveDir="/etc/justbrowsing/data"
configFile="${saveDir}/config"
cfgFile="${mntDir}/justbrowsing.cfg"
netFile="${mntDir}/networking"
lockFile="/tmp/savecfg.lock"
daemon="/tmp/savecfg.daemon"
logFile="/tmp/savecfg.log"
htmlFile="/tmp/sync.html"
delay="5"

LOG_STATUS() { echo "ERROR: $@" | tee -a "$logFile"; }

PARSE_CONFIG() {
  grep ^${1} "$configFile" 2>/dev/null | sed -e "s/^${1} = //" -e "s/^${1}=//" | tail -n 1;
}

MULTIPARSE_CONFIG() {
  grep ^${1} "$configFile" 2>/dev/null | sed -e "s/^${1} = //" -e "s/^${1}=//";
}

OVERRIDE_CFG() {
  parameter=$(eval echo \$$1);
  sed -i "/^$1/d" "$cfgFile"
  if [ ! -z "$parameter" ]; then
    IFS=" "
    for arg in $parameter; do
      echo "$1 = $arg" >> "$cfgFile"
    done
  fi
}

PACK_DATA() {
  [ -f "$netFile" ] && rm "$netFile"
  cypher="enc -aes-256-cbc -salt"
  index="/usr/share/pixmaps/jbconfig.png"
  tar -C "$saveDir" -czv networks keyrings | openssl $cypher -out "$netFile" -pass "file:$index"
}

MAKE_HTML() {
  browserPID=$(pgrep -nx x-www-browser);
  activeUser=$(ps aux | grep "$browserPID" | grep -v grep | awk '{print $1}' | grep -v root | awk NR==1);
  activeDisplay=$(ls --color=none /tmp/.X11-unix/ | sed 's/^X/:/');
  echo "<html><head><title>Saved :: jb-config</title></head>" > "$htmlFile"
  echo "<body><h1>Successfully saved justbrowsing.cfg</h1>" >> "$htmlFile"
  cat "$cfgFile" | sed ':a;N;$!ba;s/\n/<br>\n/g' >> "$htmlFile"
  [ -f "$logFile" ] &&
  echo "<h1>The following errors occured:</h1>" >> "$htmlFile" &&
  cat "$logFile" | sed ':a;N;$!ba;s/\n/<br>\n/g' >> "$htmlFile"
  echo "</body></html>" >> "$htmlFile"
}

# Request sync
if [ "$1" = "sync" ]; then
  rm "$lockFile"
elif [ "$1" = "daemon" ]; then
  touch "$daemon"
  session=$(pgrep -o $2);
  while [ -n "$session" ] && [ -f "$daemon" ]; do
    [ -f "$lockFile" ] && "$0" sync
    session=$(pgrep -o $2)
    sleep "$delay"
  done
  exit 1
else
  touch "$lockFile"
  exit 0
fi


# Load config from boot parameters
export -f PARSE_CONFIG OVERRIDE_CFG
skipcfg=$(PARSE_CONFIG skipcfg)
[ "$skipcfg" = "true" ] && exit 0

setjb-networks save 2>&1 | tee -a "$logFile"
backlight=$(PARSE_CONFIG backlight)
clean=$(PARSE_CONFIG clean)
default=$(PARSE_CONFIG default)
display=$(PARSE_CONFIG display)
email=$(PARSE_CONFIG email)
gpu=$(PARSE_CONFIG gpu)
idle=$(PARSE_CONFIG idle)
keymap=$(PARSE_CONFIG keymap)
kiosk=$(PARSE_CONFIG kiosk)
locale=$(PARSE_CONFIG locale)
mouse=$(PARSE_CONFIG mouse)
network=$(PARSE_CONFIG network)
printer=$(MULTIPARSE_CONFIG printer)
touchpad=$(PARSE_CONFIG touchpad)
url=$(PARSE_CONFIG url)
volume=$(PARSE_CONFIG volume)
zone=$(PARSE_CONFIG zone)
[ "$default" = "google-chrome" ] && default="chrome"

# Load config from persistent storage
if [ -b "$probeDevice" ]; then
  [ "$UID" = "0" ] || LOG_STATUS "Need to be root"
  mkdir -p "$mntDir" "$saveDir" || LOG_STATUS "unable to create dirs: $mntDir $saveDir"
  mount -o rw "$probeDevice" "$mntDir" || LOG_STATUS "unable to mount $probeDevice"
  touch "$cfgFile"
  sed -i 's/^M$//' "$cfgFile"
  [ -f "$cfgFile" ] || LOG_STATUS "unable to create $cfgFile"
  OVERRIDE_CFG backlight
  OVERRIDE_CFG clean
  OVERRIDE_CFG default
  OVERRIDE_CFG display
  OVERRIDE_CFG email
  OVERRIDE_CFG gpu
  OVERRIDE_CFG idle
  OVERRIDE_CFG keymap
  OVERRIDE_CFG kiosk
  OVERRIDE_CFG locale
  OVERRIDE_CFG mouse
  OVERRIDE_CFG network
  OVERRIDE_CFG printer
  OVERRIDE_CFG touchpad
  OVERRIDE_CFG url
  OVERRIDE_CFG volume
  OVERRIDE_CFG zone
  PACK_DATA
  MAKE_HTML
  umount "$mntDir" 2>/dev/null || LOG_STATUS "unable to unmount $mntDir"
  echo "==> Saved config to justbrowsing.cfg"
  su - "$activeUser" -c "DISPLAY=${activeDisplay} /usr/bin/x-www-browser file://${htmlFile}"
else
  echo "==> Notice: config not saved"
fi

### END ###
