#!/bin/bash
config="/etc/justbrowsing/data/config"

if [ ! -z "$1" ]; then
  mouse="$1"
  touchpad="$2"
fi

if [ -f "$config" ]; then
  [ -z "$mouse" ] && mouse=$(grep ^mouse "$config" 2>/dev/null | awk -F = '{print $NF}' | awk '{print $NF}')
  [ -z "$touchpad" ] && touchpad=$(grep ^touchpad "$config" 2>/dev/null | awk -F = '{print $NF}' | awk '{print $NF}')
fi

synaptics=$(which synclient 2>/dev/null)

if [ "$1" = "current" ]; then
  xset q | grep acceleration: | awk '{print $2}' | awk -F "/" '{print ($1/$2)}'
elif [ "$1" = "tap" ]; then
  [ "$touchpad" = "enabletap" ] && echo "true" || echo "false"
elif [ "$1" = "reset" ]; then
  [ ! -z "$synaptics" ] && synclient TapButton1=0 TapButton2=0 TapButton3=0
  xset m default
  sed -i '/^mouse/d' "$config"
  sed -i '/^touchpad/d' "$config"
elif [ "$touchpad" = "enabletap" ]; then
  [ ! -z "$synaptics" ] && synclient TapButton1=1 TapButton2=3 TapButton3=2
  sed -i '/^touchpad/d' "$config"
  echo "touchpad = ${touchpad}" >> "$config"
elif [ "$touchpad" = "disabletap" ]; then
  [ ! -z "$synaptics" ] && synclient TapButton1=0 TapButton2=0 TapButton3=0
  sed -i '/^touchpad/d' "$config"
elif [ ! -z "$mouse" -a "$mouse" != "touchpad" ]; then
  [ "$2" = "gtk" ] && mouse=$(echo "$mouse" | awk '{print ($1*100)"/100"}');
  xset m "$mouse"
  sed -i '/^mouse/d' "$config"
  echo "mouse = ${mouse}" >> "$config"
fi

export mouse touchpad
