#!/bin/bash
config="/etc/justbrowsing/data/config"

if [ ! -z "$1" ]; then
  printer="$1"
elif [ -f "$config" ]; then
  printer=$(grep ^printer "$config" 2>/dev/null | awk -F = '{print $NF}' | awk '{print $NF}')
fi

queryPrinters() {
  DeviceIDs=$(lpinfo --include-schemes=usb -v 2>/dev/null | grep "^direct " | awk '{print $2}');
  USB=$(echo "$DeviceIDs" | awk -F "?" '{print $1}' | sed -e 's/^usb:\/\///' -e 's/\//|/' -e 's/%20/ /g');
  Brand=$(echo "$USB" | awk -F "|" '{print $1}');
  ShortName=$(echo "$USB" | awk -F "|" '{print $2}');
  defaultBrand=$(echo "$Brand" | awk NR==1);
  [ -z "$defaultBrand" ] && defaultBrand="(none)";
}

queryDrivers() {
  PPDs=$(grep "<printer " /usr/share/gutenprint/*/xml/printers.xml | sort | grep -o -e "<printer " -e 'name=[^=]*"' -e 'manufacturer=[^=]*"' -e 'driver=[^=]*"' | sed -e 's/name="/|/g' -e 's/driver="/|/g' -e 's/manufacturer="/|/g');
  Models=$(echo $PPDs | sed -e 's/<printer |/\n/g' -e 's/" |/|/g' -e 's/" //g' -e 's/"//g' | awk -F "|" '{print $3"|"$1"|"$2}');
  OEMs=$(echo "$Models" | awk -F "|" '{print $1}' | sort -u | sed -e 's/^$/none/g');
  printRow=$(echo "$Models" | grep "^${defaultBrand}" | awk -F "|" '{print $2}' | grep -n "${ShortName}" | awk -F ":" '{print $1-1}');
}

listPrinters() {
  if [ -z "$Brand" -o -z "$ShortName" ]; then
    echo "(No USB printers detected)"
  else
    echo "$Brand $ShortName" | nl -n ln | sed 's/^/Printer#/';
  fi
}

listDrivers() { 
  if [ -z "$1" ]; then
    echo "$Models" | grep -i "^${defaultBrand}" | awk -F "|" '{print $1"|"$2"|"$2"|"$3}'
  elif [ "$1" = "OEM" ]; then
    echo "$OEMs"
  elif [ "$1" = "none" ]; then
    echo "$Models" | awk -F "|" '{print $1"|"$2"|"$2"|"$3}'
  else
    echo "$Models" | grep ^"$1" | awk -F "|" '{print $1"|"$2"|"$2"|"$3}'
  fi
}

installPrinter() {
  Driver=$(find /usr/share/cups/ -name "*$1*ppd*");
  shift;
  LineInt=$(echo "$1" | sed -e 's/Printer#//' -e 's/ //g');
  Interface=$(echo "$DeviceIDs" | awk -v line=$LineInt NR==line);
  shift;
  printName=$(echo "$@" | sed 's/ /_/g');
  lprm -
  cupsreject "$printName"
  cupsdisable "$printName"
  lpadmin -x "$printName"
  lpadmin -p "$printName" -E -v "$Interface" -P "$Driver"
  cupsenable "$printName"
  lpoptions -d "$printName"
  echo "Added Printer: $printName @ $Interface ($Driver)"
}

getPrinters() {
  myPrinters=$(lpstat -s 2>/dev/null | grep "^device " | awk -F ":" '{print $1}' | awk '{print $3}');
  favPrinter=$(lpstat -s 2>/dev/null | grep "^system " | awk -F ": " '{print $2}');
  printLine=$(echo "$myPrinters" | grep -n "$favPrinter" | awk -F ":" '{print $1}');
  if [ -z "$myPrinters" ]; then
    treePrint="(none installed)"
  else
    treePrint=$(echo "$myPrinters" | sed "${printLine}s/$/ */");
  fi
  echo "$treePrint"
}


if [ "$1" = "current" ]; then
  queryPrinters
  echo "$defaultBrand"
  listPrinters
elif [ "$1" = "saved" ]; then
  getPrinters
elif [ "$1" = "install" ]; then
  shift
  queryPrinters
  installPrinter "$@"
  sed -i '/^printer/d' "$config"
  echo "printer = ${printer}" >> "$config"
elif [ "$1" = "delete" ]; then
  shift
  lprm -
  cupsreject "$1"
  cupsdisable "$1"
  lpadmin -x "$1"
  sed -i '/^printer/d' "$config"
  echo "printer = ${printer}" >> "$config"
elif [ "$1" = "default" ]; then
  shift
  lpoptions -d "$1"
  sed -i '/^printer/d' "$config"
  echo "printer = ${printer}" >> "$config"
else
  queryPrinters
  queryDrivers
  listDrivers "$1"
fi

export printer
