#!/bin/bash
config="/etc/justbrowsing/data/config"

if [ ! -z "$1" ]; then
  display="$1"
  orientation="$2"
elif [ -f "$config" ]; then
  display=$(grep ^display "$config" 2>/dev/null | awk -F = '{print $NF}' | awk '{print $NF}')
  rotate=$(grep ^rotate "$config" 2>/dev/null | awk -F = '{print $NF}' | awk '{print $NF}')
fi

[ "$rotate" = "normal" ] && orientation="normal"
[ "$rotate" = "left" ] && orientation="left"
[ "$rotate" = "right" ] && orientation="right"
[ "$rotate" = "inverted" ] && orientation="inverted"

if [ "$1" = "current" ]; then
  shift
  unset display
  resolutions=$(xrandr 2>&1 | grep "^   " | awk '{print $1}' | sed 's/[0-9]$/&p/' | sort -nr | sed 's/p$//')
  status=$(xrandr --current 2>&1 | grep " connected [0-9]" | awk '{print $3}' | awk -F + '{print $1}')
  [ -f "$config" ] && display=$(grep ^display "$config" 2>/dev/null | awk -F = '{print $NF}' | awk '{print $NF}')
  [ "$1" != "gtk" ] && echo "$resolutions"
  [ "$1" = "gtk" -a ! -z "$display" ] && echo "$resolutions" | sed -e "1i${display} (•)" -e "1iauto" | awk '{print $0"|"$0}'
  [ "$1" = "gtk" -a -z "$display" ] && echo "$resolutions" | sed "1iauto [${status}] (•)" | awk '{print $0"|"$0}'
  exit 0
elif [ "$display" = "auto" ]; then
  monitor=$(xrandr --current 2>&1 | grep " connected [0-9]" | awk '{print $1}' | awk NR==1);
  xrandr --output "$monitor" --auto --rotate normal
  sed -i '/^display/d' "$config"
  sed -i '/^rotate/d' "$config"
elif [ ! -z "$display" -a ! -z "$orientation" ]; then
  [[ "$display" = *•* ]] && display=$(echo "$display" | sed -e 's/auto \[//' -e 's/]//' | awk -F " \\\(•)" '{print $1}');
  monitor=$(xrandr --current 2>&1 | grep " connected [0-9]" | awk '{print $1}' | awk NR==1);
  xrandr --output "$monitor" --mode "$display" --rotate "$orientation"
  sed -i '/^display/d' "$config"
  sed -i '/^rotate/d' "$config"
  echo "display = ${display}" >> "$config"
  echo "rotate = ${orientation}" >> "$config"
elif [ ! -z "$display" ]; then
  [[ "$display" = *•* ]] && display=$(echo "$display" | sed -e 's/auto \[//' -e 's/]//' | awk -F " \\\(•)" '{print $1}');
  monitor=$(xrandr --current 2>&1 | grep " connected [0-9]" | awk '{print $1}' | awk NR==1);
  xrandr --output "$monitor" --mode "$display"
  sed -i '/^display/d' "$config"
  echo "display = ${display}" >> "$config"
else
  current=$(xrandr --current 2>&1 | grep " connected [0-9]")
  display=$(echo "$current" | awk '{print $3}' | awk -F + '{print $1}');
  rotate=$(echo "$current" | awk -F "(" '{print $1}' | awk '{print $4}' | grep -v ^$);
  echo "$display:$rotate"
fi
