#!/bin/bash
config="/etc/justbrowsing/data/config"

if [ -f "$config" ]; then
  printers=$(grep ^printer "$config" 2>/dev/null | sed -e "s/^printer = //" -e "s/^printer=//")
fi

queryPrinters() {
  DeviceIDs=$(lpinfo --include-schemes=usb -v 2>/dev/null | grep "^direct " | awk '{print $2}');
  USB=$(echo "$DeviceIDs" | awk -F "?" '{print $1}' | sed -e 's/^usb:\/\///' -e 's/\//|/' -e 's/%20/ /g');
  Brand=$(echo "$USB" | awk -F "|" '{print $1}');
  ShortName=$(echo "$USB" | awk -F "|" '{print $2}');
  defaultBrand=$(echo "$Brand" | awk NR==1);
  [ -z "$defaultBrand" ] && defaultBrand="(none)";
  PPDs=$(grep "<printer " /usr/share/gutenprint/*/xml/printers.xml | sort);
  PPDs=$(echo "$PPDs" | grep -o -e "<printer " -e 'name=[^=]*"' -e 'manufacturer=[^=]*"' -e 'driver=[^=]*"' | sed -e 's/name="/|/g' -e 's/driver="/|/g' -e 's/manufacturer="/|/g');
  Models=$(echo $PPDs | sed -e 's/<printer |/\n/g' -e 's/" |/|/g' -e 's/" //g' -e 's/"//g' | awk -F "|" '{print $3"|"$1"|"$2}');
  OEMs=$(echo "$Models" | awk -F "|" '{print $1}' | sort -u | sed -e 's/^$/none/g');
  printRow=$(echo "$Models" | grep "^${defaultBrand}" | awk -F "|" '{print $2}' | grep -n "${ShortName}" | awk -F ":" '{print $1-1}');
  [ -z "$printRow" ] && printRow="0"
}

listPrinters() {
  if [ -z "$Brand" -o -z "$ShortName" ]; then
    echo "(No USB printers detected)"
  else
    echo "$Brand $ShortName" | nl -n ln | sed 's/^/Printer#/';
  fi
}

listDrivers() { 
  if [ -z "$1" -a "$defaultBrand" != "(none)" ]; then
    echo "$Models" | grep -i "^${defaultBrand}" | awk -F "|" '{print $1"|"$2"|"$2"|"$3}'
  elif [ "$1" = "OEM" ]; then
    echo "$OEMs"
  elif [ "$1" = "none" ]; then
    echo "$Models" | awk -F "|" '{print $1"|"$2"|"$2"|"$3}'
  else
    echo "$Models" | grep ^"$1" | awk -F "|" '{print $1"|"$2"|"$2"|"$3}'
  fi
}

installPrinter() {
  Driver="$1"
  [ ! -f "$Driver" ] && Driver=$(find /usr/share/cups/ -name "*$1*ppd*" | awk NR==1);
  shift;
  Interface="$1"
  LineInt=$(echo "$1" | sed -e 's/Printer#//' -e 's/ //g');
  [ "$LineInt" -ge 0 ] 2>/dev/null && Interface=$(echo "$DeviceIDs" | awk -v line=$LineInt NR==line);
  shift;
  printName=$(echo "$@" | sed 's/ /_/g');
  lprm -
  cupsreject "$printName"
  cupsdisable "$printName"
  lpadmin -x "$printName"
  lpadmin -p "$printName" -E -v "$Interface" -P "$Driver"
  cupsenable "$printName"
  lpoptions -d "$printName"
  echo "Added Printer: $printName @ $Interface ($Driver)"
}

getPrinters() {
  myPrinters=$(lpstat -s 2>/dev/null | grep "^device " | awk -F ":" '{print $1}' | awk '{print $3}');
  favPrinter=$(lpstat -s 2>/dev/null | grep "^system " | awk -F ": " '{print $2}');
  printLine=$(echo "$myPrinters" | grep -n "$favPrinter" | awk -F ":" '{print $1}');
  if [ -z "$myPrinters" ]; then
    treePrint="(none installed)"
  else
    treePrint=$(echo "$myPrinters" | sed "${printLine}s/$/ */");
  fi
  echo "$treePrint"
}

if [ "$1" = "current" ]; then
  queryPrinters
  echo "$defaultBrand"
  echo "$printRow"
  listPrinters
elif [ "$1" = "saved" ]; then
  getPrinters
elif [ "$1" = "load" ]; then
  IFS=$(echo -en "\n\b");
  for machine in $printers; do
    printName=$(echo "$machine" | awk -F "|" '{print $1}' | sed 's/^~//');
    Interface=$(echo "$machine" | awk -F "|" '{print $2}');
    Driver=$(echo "$machine" | awk -F "|" '{print $3}');
    installPrinter "$Driver" "$Interface" "$printName"
  done
elif [ "$1" = "install" ]; then
  shift
  queryPrinters
  installPrinter "$@"
  sed -i -e "s/^printer = ~/printer = /" -e "s/^printer=~/printer=/" "$config"
  sed -i -e "/^printer = ${printName}/d" -e "/^printer=${printName}/d" "$config"
  echo "printer = ~${printName}|${Interface}|${Driver}" >> "$config"
elif [ "$1" = "delete" ]; then
  shift
  printer="$1"
  lprm -
  cupsreject "$printer"
  cupsdisable "$printer"
  lpadmin -x "$printer"
  sed -i -e "/^printer = ~${printer}/d" -e "/^printer=~${printer}/d" "$config"
  sed -i -e "/^printer = ${printer}/d" -e "/^printer=${printer}/d" "$config"
  countPrinters=$(lpstat -s 2>/dev/null | grep "^device " | wc -l)
  [ "$countPrinters" -eq 1 ] && sed -i -e "s/^printer = ~/printer = /" -e "s/^printer=~/printer=/" "$config"
  [ "$countPrinters" -eq 1 ] && sed -i -e "s/^printer = /printer = ~/" -e "s/^printer=/printer=~/" "$config"
elif [ "$1" = "default" ]; then
  shift
  printer="$1"
  lpoptions -d "$printer"
  sed -i -e "s/^printer = ~/printer = /" -e "s/^printer=~/printer=/" "$config"
  sed -i -e "s/^printer = $printer/printer = ~$printer/" -e "s/^printer=$printer/printer=~$printer/" "$config"
else
  queryPrinters
  listDrivers "$1"
fi

export printer
