#!/bin/bash

userDir="/home/jbuser"
config="/etc/justbrowsing/data/config"
ffDir="$HOME/.mozilla/firefox"
ffProfile="oknp3n8p.default"
gcDir="$HOME/.config"
gcProfile="google-chrome"

[ -f "$config" ] &&
clean=$(grep ^clean "$config" 2>/dev/null | awk -F = '{print $NF}' | awk '{print $NF}')

### Note: echo -e "[XRE]\nEnableProfileMigrator=false" > /usr/lib/firefox/browser/override.ini ###

if [ "$1" = "load" -a "$clean" = "true" ]; then
  rm -rf ${ffDir}/*.default
  rm -f "${ffDir}/profiles.ini"
  rm -rf "${ffDir}/${ffProfile}"
  rm -rf "${gcDir}/${gcProfile}"
elif [ "$1" = "load" ]; then
  rm -rf ${ffDir}/*.default
  cd "$ffDir"
  [ ! -f "profiles.ini" ] && ln -s profiles.jb profiles.ini
  [ ! -d "$ffProfile" ] && ln -s firefox.jb "$ffProfile"
  cd "$gcDir"
  [ ! -d "$gcProfile" ] && ln -s google-chrome.jb "$gcProfile"
fi

if [ "$1" = "true" ]; then
  clean="true"
  sed -i '/^clean/d' "$config"
  echo "clean = true" >> "$config"
elif [ "$1" = "false" ]; then
  clean="false"
  sed -i '/^clean/d' "$config"
fi

echo "$clean"
