#!/bin/bash
config="/etc/justbrowsing/data/config"

if [ "$1" = "load" ]; then
  shift && load="true"
fi

if [ ! -z "$1" ]; then
  email="$1"
elif [ -f "$config" ]; then
  email=$(grep ^email "$config" 2>/dev/null | awk -F = '{print $NF}' | awk '{print $NF}')
fi

email=$(echo "$email" | grep -o -e "^Google$" -e "^Microsoft$" -e "^Yahoo$" -e "^Zoho$");

if [ "$load" = "true" ]; then
  [ -z "$email" ] && email="index"
  x-www-browser /apps/email/${email}.html
elif [[ "$1" = *none* ]]; then
  sed -i '/^email/d' "$config"
elif [ ! -z "$email" ]; then
  sed -i '/^email/d' "$config"
  echo "email = ${email}" >> "$config"
  echo "$email"
fi
