#!/bin/bash

config="/etc/justbrowsing/data/config"

if [ -f "$config" ]; then
  gpu=$(grep ^gpu "$config" 2>/dev/null | awk -F = '{print $NF}' | awk '{print $NF}')
fi

if [ "$1" = "vbox-daemon" -a "$gpu" = "vbox" ]; then
  VBoxClient-all &
  rdp-cursors
  #rm $HOME/.Xresources
elif [ "$1" = "load" -a "$gpu" = "vbox" ]; then
  modprobe -a vboxguest vboxsf vboxvideo
  systemctl start vboxservice.service
elif [ "$1" = "load" -a "$gpu" = "vmware" ]; then
  systemctl start vmtoolsd.service
elif [ "$1" = "load" -a "$gpu" = "qxl" ]; then
  echo "qxl: nothing to do"
fi

[ ! -z "$1" ] && gpu="$1"
gpu=$(echo "$gpu" | grep -o -e "^none$" -e "^vbox$" -e "^qxl$" -e "^vmware$");

if [ -z "$1" ]; then
  echo "$gpu"
elif [ "$gpu" = "none" ]; then
  sed -i '/^gpu/d' "$config"
elif [ ! -z "$gpu" ]; then
  sed -i '/^gpu/d' "$config"
  echo "gpu = ${gpu}" >> "$config"
fi
