#!/bin/bash

config="/etc/justbrowsing/data/config"
adeskbar="$HOME/.config/adeskbar/default.cfg"

if [ -f "$config" ]; then
  default=$(grep ^default "$config" | awk -F = '{print $NF}' | awk '{print $NF}')
fi

if [ ! -z "$1" -a "$1" != "load" ]; then
  default="$1"
fi

setDefault() {
  [ -z "$default" ] && default="firefox"
  if [ "$default" = "firefox" ]; then
    rm /tmp/google-chrome.lock
  elif [ "$default" = "chrome" ]; then
    default="google-chrome"
    rm /tmp/firefox.lock
  fi

  touch /tmp/${default}.lock
  cp /opt/justbrowsing/${default}.cfg "$adeskbar"
}

if [ -z "$1" ]; then
  [ -z "$default" ] && default="firefox"
  echo "$default"
elif [ "$1" = "load" ]; then
  setDefault
elif [ ! -z "$default" ]; then
  sed -i '/^default/d' "$config"
  echo "default = ${default}" >> "$config"
  setDefault
fi
